### ISSUE TITLE
[JOURNAL] Week 01 (Pradyuman)

### ISSUE THREAD

**Issue by pradyuman-verma** [pinheadmz/bcoin-guide#2]
---
Name: Pradyuman Verma

Questions : 
  **Q1: What are `tests`?**
-> `test` are used for various things like to prevent regression and also for documentation.
  **Q2: Difference between `network=regtest` and `network=testnet`?**
-> `testnet` is out on the internet, but `regtest` is on local. `regtest` do not connects to any external nodes. It is all in your local computer only while `testnet` is more like `mainet`. You are synced to a blockchain and can transfer coins to any other node.
  **Q3: Bwallet-cli vs bcoin-cli?**
-> `bcoin` run two servers, one for wallet and the other for full node. Each server has two API commands to fetch JSON data.

We also discussed some questions from the week1 guide;
**Q1: When you requested an address, you got a JSON blob with data like `account`, `branch` and `index`. Do you know what these mean?**
-> the JSON response is like this-
```
{
  "name": "default",
  "account": 0,
  "branch": 0,
  "index": 3,
  "witness": false,
  "nested": false,
  "publicKey": "03af169e5a186bbd7b380cb4553c72af243e18f243785b1597f192bbedd4a94fc3",
  "script": null,
  "program": null,
  "type": "pubkeyhash",
  "address": "n2eoT9D8txT5ZymDvCFPA8PHs2CmTV6oJT"
}
```
  where, 
  `account` = This splits the keyspace into independent user identities, so the wallet never mixes the coins across different accounts. Users can use these accounts to organize the funds in the same fashion as bank accounts; for donation purposes (where all addresses are considered public), for saving purposes, for common expenses etc. Accounts are numbered from index 0 in a sequentially increasing manner. This number is used as a child index in BIP32 derivation. 
  `branch` = According to BIP44, an account has two children (known as branches): the first for receiving addresses and the second for change addresses. Here in bcoin, there is also a third branch for nested segwit addresses. (bcoin does not implement BIPS 49 and 84 yet.) These three branches can, in turn, have as many children as needed. 
  `index` = index of address in the branch.

**Q2. What did you notice was different about the first wallet address vs the SegWit address?**
-> In the first wallet, the wallet address starts with m..., which is a bech32 address, while the second wallet has a segwit address that starts with bc... which is a base58check.

**Q3. When you sent the transaction, you got a big JSON blob back with data like `fee`, `rate`, and `path`. What do these mean?**
-> `rate` is the transaction fees in sat/byte, `fee` is the total transaction fee (rate * size), and a `path` is an object which contains information on a particular path to a key in the tree hierarchy of the wallet.

**Q4. When you checked your wallet balance, there is confirmed and unconfirmed. What's the difference? (bonus: how does bcoin use the terms differently than Bitcoin Core?)**
-> In `bcoin`, `confirmed` refers to the total balance of coins confirmed in the blockchain, `unconfirmed` refers to the total confirmed plus unconfirmed transaction in the mempool, or we can say that `unconfirmed is the total future balance.

**What I learned**
- many bcoin commands, and their implementation in javascript, and using curl.
- about BIP 44, BIP 39, BIP 43 for hierarchical deterministic wallets.
- BIP 141, 144, 143 for segwit.

I wrote a [blog](https://pradyuman.hashnode.dev/getting-started-with-bcoin-javascript-implementation-of-full-node) on this you can also check it out.
---

**Comment by pinheadmz** [comment]
> -> In the first wallet, the wallet address starts with m..., which is a bech32 address, while the second wallet has a segwit address that starts with bc... which is a base58check.

You got these backwards ;-)

base58: `n2eoT9D8txT5ZymDvCFPA8PHs2CmTV6oJT`
bech32: `bcrt1qggre40we5qdeenzudq3yz0qxee8qc57s2fqygy`

Great work, thanks for posting!
