### ISSUE TITLE
[JOURNAL] Week 03 (pradyuman)

### ISSUE THREAD

**Issue by pradyuman-verma** [pinheadmz/bcoin-guide#5]
**What I learned** :
- This week, we hopped into the code base, and went through some files containing code about `JSON-rpc API` and `rest API`.
- I looked at test files of this code implementation, and tried breaking the code and curing it afterwords.
- Also made some changes in the test files to increase code coverage and raised a PR (check it [here](https://github.com/bcoin-org/bcoin/pull/1026))
- And I resolved this [issue](https://github.com/bcoin-org/bcoin/issues/1028) by making changes to blockchain directory files. ([here](https://github.com/bcoin-org/bcoin/pull/1029) is the PR that resolves the issue).
- Last but not least, I did set up my bcoin node in `spv` mode, and checked commands that do work in this mode.

**Questions** : 
**1. What are different types of logger levels available on `bcoin` ?**
-> So, `bcoin` support six types (technically five). These are - none, error, info, warning, debug, spam.
You can check those [here](https://github.com/bcoin-org/blgr/blob/master/lib/logger.js#L878).
`Logger.levels = {
  NONE: 0,
  ERROR: 1,
  WARNING: 2,
  INFO: 3,
  DEBUG: 4,
  SPAM: 5
};
`
To set the logger level manually, you can use `--log-level=info` while starting your bcoin node.

**Comment by pinheadmz** [comment]
Great thanks for your journal and for the pull request!
